(() => {
  const selector = document.querySelector('[data-language]');
  if (!selector) return;

  const fr = {
    'Language':'Langue','Skip to content':'Aller au contenu','ORVECT home':'Accueil ORVECT','ORVECT back to top':'ORVECT — retour en haut','Main navigation':'Navigation principale','The approach':'L’approche','The prototype':'Le prototype','The vision':'La vision',"Let's talk":'Échangeons',
    'INDEPENDENT THINKING. AUTOMOTIVE INTELLIGENCE.':'PENSÉE INDÉPENDANTE. INTELLIGENCE AUTOMOBILE.','Beyond':'Au-delà','the fault':'du code','code.':'défaut.','A new direction for automotive diagnostics.':'Une nouvelle voie pour le diagnostic automobile.','Built around context. Grounded in evidence.':'Construite autour du contexte. Ancrée dans les preuves.','Designed to keep the technician in control.':'Conçue pour laisser le technicien aux commandes.','Explore the prototype':'Explorer le prototype','Our approach':'Notre approche',
    'ORVECT / INTELLIGENCE CORE':'ORVECT / CŒUR D’INTELLIGENCE','Abstract three-dimensional sculpture of three diagnostic layers: context, evidence and explanation. Not a vehicle component.':'Sculpture tridimensionnelle abstraite représentant trois couches du diagnostic : contexte, preuves et explication. Il ne s’agit pas d’une pièce automobile.','CONTEXT / EVIDENCE / CLARITY':'CONTEXTE / PREUVES / CLARTÉ','REVEAL THE LAYERS':'RÉVÉLER LES COUCHES','Separation of the three illustrative layers':'Séparation des trois couches illustratives','Pause motion':'Suspendre le mouvement','CONCEPT SCULPTURE · NOT A VEHICLE SIMULATION':'SCULPTURE CONCEPTUELLE · PAS UNE SIMULATION AUTOMOBILE','STATIC EDITION · CONCEPT SCULPTURE':'VERSION STATIQUE · SCULPTURE CONCEPTUELLE','EARLY TECHNICAL PROTOTYPE':'PREMIER PROTOTYPE TECHNIQUE','CONCEIVED IN STOCKHOLM':'CONÇU À STOCKHOLM','SCROLL TO EXPLORE ↓':'DÉFILER POUR EXPLORER ↓',
    '01 / THE APPROACH':'01 / L’APPROCHE','FROM SIGNAL TO UNDERSTANDING':'DU SIGNAL À LA COMPRÉHENSION','A code is':'Un code est','the beginning.':'le début.','Not the answer.':'Pas la réponse.','The ambition is simple: make the reasoning behind a diagnostic result as visible as the result itself.':'L’ambition est simple : rendre le raisonnement derrière un résultat de diagnostic aussi visible que le résultat lui-même.','ORVECT is building a context layer for independent workshops. Vehicle configuration, source provenance and evidence come before an AI explanation.':'ORVECT construit une couche de contexte pour les garages indépendants. La configuration du véhicule, la provenance des sources et les preuves précèdent toute explication par l’IA.','See what sits beneath':'Voir ce qui se trouve dessous',
    '01 — CONTEXT':'01 — CONTEXTE','The right vehicle.':'Le bon véhicule.','The right scope.':'Le bon périmètre.','Keep the vehicle, engine, ECU and diagnostic namespace visible. An uncertain match stays uncertain.':'Garder visibles le véhicule, le moteur, le calculateur et l’espace de diagnostic. Une correspondance incertaine reste incertaine.','02 — EVIDENCE':'02 — PREUVES','Show the source.':'Montrer la source.','Respect the limits.':'Respecter les limites.','Preserve provenance and compatibility. An unavailable definition is reported as unavailable.':'Préserver la provenance et la compatibilité. Une définition indisponible est signalée comme telle.','03 — CLARITY':'03 — CLARTÉ','Explain the reasoning.':'Expliquer le raisonnement.','Keep human oversight.':'Maintenir le contrôle humain.','Separate interpretation from critical decisions. Zero hypotheses is a valid diagnostic outcome.':'Séparer l’interprétation des décisions critiques. Zéro hypothèse est un résultat de diagnostic valable.',
    '02 / INSIDE THE PROTOTYPE':'02 / DANS LE PROTOTYPE','REAL INTERFACE. SYNTHETIC DEMO.':'INTERFACE RÉELLE. DÉMO SYNTHÉTIQUE.','Confidence starts':'La confiance commence','with knowing':'par reconnaître','what you don\'t know.':'ce que l’on ignore.','This demonstration shows a deliberate boundary: when the definition and evidence are missing, the system asks for human review.':'Cette démonstration montre une limite volontaire : lorsque la définition et les preuves manquent, le système demande une revue humaine.','LOCAL DEMO / NO CUSTOMER DATA':'DÉMO LOCALE / AUCUNE DONNÉE CLIENT','PROTOTYPE':'PROTOTYPE','Actual synthetic prototype result: manufacturer-specific definition unavailable, zero hypotheses, Safety Engine unknown and human review required.':'Résultat réel du prototype synthétique : définition constructeur indisponible, zéro hypothèse, Safety Engine indéterminé et revue humaine requise.','Captured 5 September 2026 under the previous working name, DiagPilot. Deterministic mock demonstration; not a live ECU scan or validated diagnosis.':'Capture du 5 septembre 2026 sous l’ancien nom de travail DiagPilot. Démonstration déterministe simulée ; ni lecture calculateur en direct, ni diagnostic validé.','THE BOUNDARY IS PART OF THE PRODUCT.':'LA LIMITE FAIT PARTIE DU PRODUIT.','A missing definition should never become an invented answer.':'Une définition manquante ne doit jamais devenir une réponse inventée.',
    '03 / BUILT WITH BOUNDARIES':'03 / CONÇU AVEC DES LIMITES','ONE PRODUCT. DISTINCT RESPONSIBILITIES.':'UN PRODUIT. DES RESPONSABILITÉS DISTINCTES.','Intelligence.':'L’intelligence.','With structure.':'Avec une structure.','Three distinct layers within one modular application. Fluency is not a substitute for evidence.':'Trois couches distinctes dans une application modulaire. La fluidité ne remplace pas les preuves.','01 / DIAGNOSTIC ENGINE':'01 / MOTEUR DE DIAGNOSTIC','Evidence before hypotheses.':'Les preuves avant les hypothèses.','Structured diagnostic state, explicit ambiguity and no obligation to produce an answer.':'État de diagnostic structuré, ambiguïté explicite et aucune obligation de produire une réponse.','02 / SAFETY ENGINE':'02 / MOTEUR DE SÉCURITÉ','Conservative by design.':'Prudent par conception.','Critical boundaries belong to rules. When no reliable rule exists: unknown / human review.':'Les limites critiques relèvent de règles. Sans règle fiable : indéterminé / revue humaine.','03 / EXPLANATION LAYER':'03 / COUCHE D’EXPLICATION','Language, not authority.':'Le langage, pas l’autorité.','The LLM communicates within those boundaries. It does not independently authorize driving or a definitive replacement.':'Le LLM communique dans ces limites. Il n’autorise pas de manière autonome la conduite ou un remplacement définitif.',
    '04 / THE DIRECTION':'04 / LA DIRECTION','DEPTH BEFORE BREADTH':'LA PROFONDEUR AVANT L’ÉTENDUE','Start focused.':'Commencer ciblé.','Think beyond.':'Voir plus loin.','Volkswagen Group is our intended first specialist focus.':'Le groupe Volkswagen constitue notre premier axe de spécialisation envisagé.','The next step is licensed diagnostic depth and structured workshop validation — not a claim of coverage we have yet to earn.':'La prochaine étape consiste à approfondir les données sous licence et la validation structurée en atelier — sans revendiquer une couverture qu’il reste à mériter.','Intended brand focus':'Marques ciblées','Commercial Vehicles':'Véhicules Utilitaires','Target scope only. No manufacturer affiliation, partnership or admitted licensed VAG production corpus today. Hardware integration and real-workshop validation remain future work.':'Périmètre cible uniquement. À ce jour, aucune affiliation constructeur, aucun partenariat ni corpus VAG de production sous licence déclaré. L’intégration matérielle et la validation en atelier restent à venir.','NOW':'MAINTENANT','A technical foundation.':'Une base technique.','Context, provenance, evidence gates and a local demonstration.':'Contexte, provenance, filtres de preuves et démonstration locale.','NEXT':'ENSUITE','Licensed diagnostic depth.':'Des données de diagnostic sous licence.','Secure reuse rights and validate a real production data profile.':'Sécuriser les droits de réutilisation et valider un véritable profil de données de production.','THEN':'PUIS','Proof in the workshop.':'La preuve en atelier.','Structured pilots, documented feedback and measured outcomes.':'Des pilotes structurés, des retours documentés et des résultats mesurés.',
    '05 / THE FOUNDER':'05 / LE FONDATEUR','BUILDING FROM STOCKHOLM':'DÉVELOPPÉ DEPUIS STOCKHOLM','Founder / ORVECT':'Fondateur / ORVECT','Automotive curiosity.':'Curiosité automobile.','Entrepreneurial intent.':'Ambition entrepreneuriale.','Business and Economics student at the Stockholm School of Economics, independent web product builder and founder of cross-border automotive association Col de l’Est.':'Étudiant en économie et gestion à la Stockholm School of Economics, créateur indépendant de produits web et fondateur de l’association automobile transfrontalière Col de l’Est.','Building ORVECT with a clear next priority: licensed data and documented technician validation.':'ORVECT avance avec une priorité claire : des données sous licence et une validation documentée par les techniciens.','Save my contact':'Enregistrer mon contact',
    'INVESTORS. WORKSHOPS. DATA PROVIDERS.':'INVESTISSEURS. GARAGES. FOURNISSEURS DE DONNÉES.',"Let's move":'Faisons avancer','diagnostics':'le diagnostic','forward.':'ensemble.','Challenge the thesis.':'Mettez la vision à l’épreuve.','Help shape what comes next.':'Aidez à construire la suite.','Start a conversation':'Démarrer une conversation','Automotive intelligence.':'Intelligence automobile.','Grounded in evidence.':'Ancrée dans les preuves.','© 2026 NOLANN PETRI / ORVECT BRAND CONCEPT':'© 2026 NOLANN PETRI / CONCEPT DE MARQUE ORVECT','PUBLIC PROTOTYPE PREVIEW':'APERÇU PUBLIC DU PROTOTYPE','BACK TO TOP ↑':'RETOUR EN HAUT ↑'
  };

  const sv = {
    'Language':'Språk','Skip to content':'Gå till innehållet','ORVECT home':'ORVECT startsida','ORVECT back to top':'ORVECT — tillbaka till toppen','Main navigation':'Huvudnavigering','The approach':'Metoden','The prototype':'Prototypen','The vision':'Visionen',"Let's talk":'Låt oss prata',
    'INDEPENDENT THINKING. AUTOMOTIVE INTELLIGENCE.':'SJÄLVSTÄNDIGT TÄNKANDE. FORDONSINTELLIGENS.','Beyond':'Bortom','the fault':'själva','code.':'felkoden.','A new direction for automotive diagnostics.':'En ny riktning för fordonsdiagnostik.','Built around context. Grounded in evidence.':'Byggd kring sammanhang. Grundad i bevis.','Designed to keep the technician in control.':'Utformad för att låta teknikern behålla kontrollen.','Explore the prototype':'Utforska prototypen','Our approach':'Vår metod',
    'ORVECT / INTELLIGENCE CORE':'ORVECT / INTELLIGENSKÄRNA','Abstract three-dimensional sculpture of three diagnostic layers: context, evidence and explanation. Not a vehicle component.':'Abstrakt tredimensionell skulptur av tre diagnostiska lager: sammanhang, bevis och förklaring. Inte en fordonskomponent.','CONTEXT / EVIDENCE / CLARITY':'SAMMANHANG / BEVIS / TYDLIGHET','REVEAL THE LAYERS':'VISA LAGREN','Separation of the three illustrative layers':'Separation av de tre illustrativa lagren','Pause motion':'Pausa rörelsen','CONCEPT SCULPTURE · NOT A VEHICLE SIMULATION':'KONCEPTSKULPTUR · INGEN FORDONSSIMULERING','STATIC EDITION · CONCEPT SCULPTURE':'STATISK VERSION · KONCEPTSKULPTUR','EARLY TECHNICAL PROTOTYPE':'TIDIG TEKNISK PROTOTYP','CONCEIVED IN STOCKHOLM':'SKAPAD I STOCKHOLM','SCROLL TO EXPLORE ↓':'SKROLLA FÖR ATT UTFORSKA ↓',
    '01 / THE APPROACH':'01 / METODEN','FROM SIGNAL TO UNDERSTANDING':'FRÅN SIGNAL TILL FÖRSTÅELSE','A code is':'En kod är','the beginning.':'början.','Not the answer.':'Inte svaret.','The ambition is simple: make the reasoning behind a diagnostic result as visible as the result itself.':'Ambitionen är enkel: gör resonemanget bakom ett diagnosresultat lika synligt som själva resultatet.','ORVECT is building a context layer for independent workshops. Vehicle configuration, source provenance and evidence come before an AI explanation.':'ORVECT bygger ett sammanhangslager för oberoende verkstäder. Fordonskonfiguration, källornas ursprung och bevis kommer före en AI-förklaring.','See what sits beneath':'Se vad som finns under ytan',
    '01 — CONTEXT':'01 — SAMMANHANG','The right vehicle.':'Rätt fordon.','The right scope.':'Rätt omfattning.','Keep the vehicle, engine, ECU and diagnostic namespace visible. An uncertain match stays uncertain.':'Håll fordon, motor, styrenhet och diagnostiskt namnutrymme synliga. En osäker matchning förblir osäker.','02 — EVIDENCE':'02 — BEVIS','Show the source.':'Visa källan.','Respect the limits.':'Respektera gränserna.','Preserve provenance and compatibility. An unavailable definition is reported as unavailable.':'Bevara ursprung och kompatibilitet. En definition som saknas rapporteras som otillgänglig.','03 — CLARITY':'03 — TYDLIGHET','Explain the reasoning.':'Förklara resonemanget.','Keep human oversight.':'Behåll mänsklig kontroll.','Separate interpretation from critical decisions. Zero hypotheses is a valid diagnostic outcome.':'Skilj tolkning från kritiska beslut. Noll hypoteser är ett giltigt diagnosresultat.',
    '02 / INSIDE THE PROTOTYPE':'02 / INUTI PROTOTYPEN','REAL INTERFACE. SYNTHETIC DEMO.':'VERKLIGT GRÄNSSNITT. SYNTETISK DEMO.','Confidence starts':'Tillförlitlighet börjar','with knowing':'med att veta','what you don\'t know.':'vad man inte vet.','This demonstration shows a deliberate boundary: when the definition and evidence are missing, the system asks for human review.':'Denna demonstration visar en avsiktlig gräns: när definition och bevis saknas begär systemet manuell granskning.','LOCAL DEMO / NO CUSTOMER DATA':'LOKAL DEMO / INGA KUNDDATA','PROTOTYPE':'PROTOTYP','Actual synthetic prototype result: manufacturer-specific definition unavailable, zero hypotheses, Safety Engine unknown and human review required.':'Verkligt syntetiskt prototypresultat: tillverkarspecifik definition saknas, noll hypoteser, okänd status i Safety Engine och manuell granskning krävs.','Captured 5 September 2026 under the previous working name, DiagPilot. Deterministic mock demonstration; not a live ECU scan or validated diagnosis.':'Skärmbild från 5 september 2026 under det tidigare arbetsnamnet DiagPilot. Deterministisk simulerad demonstration; ingen direkt ECU-avläsning eller validerad diagnos.','THE BOUNDARY IS PART OF THE PRODUCT.':'GRÄNSEN ÄR EN DEL AV PRODUKTEN.','A missing definition should never become an invented answer.':'En saknad definition får aldrig bli ett påhittat svar.',
    '03 / BUILT WITH BOUNDARIES':'03 / BYGGD MED GRÄNSER','ONE PRODUCT. DISTINCT RESPONSIBILITIES.':'EN PRODUKT. TYDLIGA ANSVARSOMRÅDEN.','Intelligence.':'Intelligens.','With structure.':'Med struktur.','Three distinct layers within one modular application. Fluency is not a substitute for evidence.':'Tre tydliga lager i en modulär applikation. Språklig flyt ersätter inte bevis.','01 / DIAGNOSTIC ENGINE':'01 / DIAGNOSMOTOR','Evidence before hypotheses.':'Bevis före hypoteser.','Structured diagnostic state, explicit ambiguity and no obligation to produce an answer.':'Strukturerad diagnosstatus, uttrycklig osäkerhet och inget krav på att ge ett svar.','02 / SAFETY ENGINE':'02 / SÄKERHETSMOTOR','Conservative by design.':'Försiktig genom sin utformning.','Critical boundaries belong to rules. When no reliable rule exists: unknown / human review.':'Kritiska gränser styrs av regler. När ingen tillförlitlig regel finns: okänt / manuell granskning.','03 / EXPLANATION LAYER':'03 / FÖRKLARINGSLAGER','Language, not authority.':'Språk, inte auktoritet.','The LLM communicates within those boundaries. It does not independently authorize driving or a definitive replacement.':'LLM kommunicerar inom dessa gränser. Den godkänner inte självständigt körning eller ett definitivt komponentbyte.',
    '04 / THE DIRECTION':'04 / RIKTNINGEN','DEPTH BEFORE BREADTH':'DJUP FÖRE BREDD','Start focused.':'Börja fokuserat.','Think beyond.':'Tänk längre.','Volkswagen Group is our intended first specialist focus.':'Volkswagen-koncernen är vårt avsedda första specialistområde.','The next step is licensed diagnostic depth and structured workshop validation — not a claim of coverage we have yet to earn.':'Nästa steg är licensierat diagnosdjup och strukturerad verkstadsvalidering — inte ett påstående om täckning som vi ännu inte har förtjänat.','Intended brand focus':'Avsedda märken','Commercial Vehicles':'Transportbilar','Target scope only. No manufacturer affiliation, partnership or admitted licensed VAG production corpus today. Hardware integration and real-workshop validation remain future work.':'Endast avsedd omfattning. I dag finns ingen tillverkaranknytning, inget partnerskap och ingen deklarerad licensierad VAG-produktionsdata. Hårdvaruintegration och validering i riktiga verkstäder återstår.','NOW':'NU','A technical foundation.':'En teknisk grund.','Context, provenance, evidence gates and a local demonstration.':'Sammanhang, ursprung, beviskontroller och en lokal demonstration.','NEXT':'NÄSTA','Licensed diagnostic depth.':'Licensierat diagnosdjup.','Secure reuse rights and validate a real production data profile.':'Säkra återanvändningsrättigheter och validera en verklig produktionsdataprofil.','THEN':'SEDAN','Proof in the workshop.':'Bevis i verkstaden.','Structured pilots, documented feedback and measured outcomes.':'Strukturerade piloter, dokumenterad återkoppling och mätbara resultat.',
    '05 / THE FOUNDER':'05 / GRUNDAREN','BUILDING FROM STOCKHOLM':'BYGGS FRÅN STOCKHOLM','Founder / ORVECT':'Grundare / ORVECT','Automotive curiosity.':'Nyfikenhet på fordon.','Entrepreneurial intent.':'Entreprenöriell drivkraft.','Business and Economics student at the Stockholm School of Economics, independent web product builder and founder of cross-border automotive association Col de l’Est.':'Student i Business & Economics vid Handelshögskolan i Stockholm, oberoende webproduktbyggare och grundare av den gränsöverskridande bilföreningen Col de l’Est.','Building ORVECT with a clear next priority: licensed data and documented technician validation.':'ORVECT byggs med en tydlig nästa prioritet: licensierade data och dokumenterad validering av tekniker.','Save my contact':'Spara min kontakt',
    'INVESTORS. WORKSHOPS. DATA PROVIDERS.':'INVESTERARE. VERKSTÄDER. DATALEVERANTÖRER.',"Let's move":'Låt oss föra','diagnostics':'diagnostiken','forward.':'framåt.','Challenge the thesis.':'Utmana tesen.','Help shape what comes next.':'Var med och forma nästa steg.','Start a conversation':'Starta en dialog','Automotive intelligence.':'Fordonsintelligens.','Grounded in evidence.':'Grundad i bevis.','© 2026 NOLANN PETRI / ORVECT BRAND CONCEPT':'© 2026 NOLANN PETRI / ORVECT VARUMÄRKESKONCEPT','PUBLIC PROTOTYPE PREVIEW':'OFFENTLIG FÖRHANDSVISNING AV PROTOTYP','BACK TO TOP ↑':'TILLBAKA TILL TOPPEN ↑'
  };

  Object.assign(fr, {
    'ORVECT / VEHICLE INTELLIGENCE':'ORVECT / INTELLIGENCE AUTOMOBILE', 'Pause effects':'Suspendre les effets', 'Resume effects':'Reprendre les effets',
    'LOOK BENEATH THE SURFACE':'VOIR AU-DELÀ DES APPARENCES', 'Every signal.':'Chaque signal.', 'A bigger picture.':'Une vue d’ensemble.',
    'Explore the connections between the vehicle, its systems and the evidence.':'Explorez les liens entre le véhicule, ses systèmes et les preuves.',
    '01 / CONTEXT':'01 / CONTEXTE','02 / EVIDENCE':'02 / PREUVES','03 / CLARITY':'03 / CLARTÉ',
    'Vehicle configuration':'Configuration véhicule','Connected signals':'Signaux reliés','Human judgement':'Jugement humain',
    'CONCEPT VISUALISATION · SCROLL TO EXPLORE':'VISUALISATION CONCEPTUELLE · DÉFILER POUR EXPLORER',
    'FROM COMPLEXITY TO CLARITY':'DE LA COMPLEXITÉ À LA CLARTÉ','Give the signals':'Donner aux signaux','a clear meaning.':'un sens clair.',
    'A visual rhythm for intelligence in motion. Always grounded in the evidence you provide.':'Un rythme visuel pour une intelligence en mouvement. Toujours ancrée dans les preuves que vous apportez.',
    'The intelligence.':'L’intelligence.','The workspace.':'L’espace de travail.',
    'Discover the diagnostic workspace and the workshop cases that help structure its knowledge.':'Découvrez l’espace de diagnostic et les cas atelier qui contribuent à structurer ses connaissances.',
    'Product previews':'Aperçus du produit','Diagnostic workspace':'Espace diagnostic','Workshop knowledge':'Savoir atelier',
    'ORVECT prototype interface':'Interface du prototype ORVECT','Actual ORVECT interface. Prototype preview, not a live diagnostic session.':'Interface réelle ORVECT. Aperçu du prototype, pas une session de diagnostic en direct.',
    'Open the prototype':'Ouvrir le prototype'
  });
  Object.assign(sv, {
    'ORVECT / VEHICLE INTELLIGENCE':'ORVECT / FORDONSINTELLIGENS','Pause effects':'Pausa effekter','Resume effects':'Återuppta effekter',
    'LOOK BENEATH THE SURFACE':'SE UNDER YTAN','Every signal.':'Varje signal.','A bigger picture.':'En större helhet.',
    'Explore the connections between the vehicle, its systems and the evidence.':'Utforska sambanden mellan fordonet, dess system och bevisen.',
    '01 / CONTEXT':'01 / SAMMANHANG','02 / EVIDENCE':'02 / BEVIS','03 / CLARITY':'03 / TYDLIGHET',
    'Vehicle configuration':'Fordonskonfiguration','Connected signals':'Sammankopplade signaler','Human judgement':'Mänskligt omdöme',
    'CONCEPT VISUALISATION · SCROLL TO EXPLORE':'KONCEPTVISUALISERING · SKROLLA FÖR ATT UTFORSKA',
    'FROM COMPLEXITY TO CLARITY':'FRÅN KOMPLEXITET TILL TYDLIGHET','Give the signals':'Ge signalerna','a clear meaning.':'en tydlig mening.',
    'A visual rhythm for intelligence in motion. Always grounded in the evidence you provide.':'En visuell rytm för intelligens i rörelse. Alltid grundad i bevisen du tillför.',
    'The intelligence.':'Intelligensen.','The workspace.':'Arbetsytan.',
    'Discover the diagnostic workspace and the workshop cases that help structure its knowledge.':'Upptäck diagnostikens arbetsyta och verkstadsfallen som hjälper till att strukturera kunskapen.',
    'Product previews':'Produktförhandsvisningar','Diagnostic workspace':'Diagnostikens arbetsyta','Workshop knowledge':'Verkstadskunskap',
    'ORVECT prototype interface':'ORVECT-prototypens gränssnitt','Actual ORVECT interface. Prototype preview, not a live diagnostic session.':'ORVECTs faktiska gränssnitt. Prototypförhandsvisning, inte en pågående diagnostiksession.',
    'Open the prototype':'Öppna prototypen'
  });
  fr.Home = 'Accueil';
  sv.Home = 'Hem';
  const dictionaries = {en:{},fr,sv};
  const originals = new WeakMap();
  const attributeOriginals = new WeakMap();

  function translate(node, dictionary) {
    if (node.nodeType === Node.TEXT_NODE) {
      const raw = originals.get(node) ?? node.nodeValue;
      originals.set(node, raw);
      const trimmed = raw.trim();
      if (trimmed) node.nodeValue = raw.replace(trimmed, dictionary[trimmed] ?? trimmed);
      return;
    }
    if (!(node instanceof Element) || node.matches('script,style')) return;
    ['aria-label','alt'].forEach(attribute => {
      if (!node.hasAttribute(attribute)) return;
      let saved = attributeOriginals.get(node);
      if (!saved) { saved = {}; attributeOriginals.set(node, saved); }
      saved[attribute] ??= node.getAttribute(attribute);
      node.setAttribute(attribute, dictionary[saved[attribute]] ?? saved[attribute]);
    });
    [...node.childNodes].forEach(child => translate(child, dictionary));
  }

  function apply(requested) {
    const language = dictionaries[requested] ? requested : 'en';
    const dictionary = dictionaries[language];
    const metadata = {
      en:['ORVECT — Beyond the fault code.','ORVECT is building automotive intelligence grounded in evidence. Vehicle context, traceable sources and human oversight for independent workshops.','Automotive intelligence. Grounded in evidence. Discover the early technical prototype.'],
      fr:['ORVECT — Au-delà du code défaut.','ORVECT développe une intelligence automobile ancrée dans les preuves : contexte véhicule, sources traçables et contrôle humain pour les garages indépendants.','Intelligence automobile. Ancrée dans les preuves. Découvrez le premier prototype technique.'],
      sv:['ORVECT — Bortom felkoden.','ORVECT bygger fordonsintelligens grundad i bevis: fordonssammanhang, spårbara källor och mänsklig kontroll för oberoende verkstäder.','Fordonsintelligens. Grundad i bevis. Upptäck den tidiga tekniska prototypen.']
    }[language];
    document.documentElement.lang = language;
    selector.value = language;
    translate(document.body, dictionary);
    const currentPage = document.querySelector('.nav nav [aria-current="page"]');
    const pageTitle = currentPage?.getAttribute('href') !== 'index.html' ? `ORVECT — ${currentPage.textContent}` : metadata[0];
    document.title = pageTitle;
    document.querySelector('meta[name="description"]')?.setAttribute('content', metadata[1]);
    document.querySelector('meta[property="og:title"]')?.setAttribute('content', pageTitle);
    document.querySelector('meta[property="og:description"]')?.setAttribute('content', metadata[2]);
    localStorage.setItem('orvect-landing-language', language);
  }

  const observer = new MutationObserver(records => records.forEach(record => record.addedNodes.forEach(node => translate(node, dictionaries[selector.value]))));
  observer.observe(document.body, {childList:true,subtree:true});
  selector.addEventListener('change', () => apply(selector.value));
  apply(localStorage.getItem('orvect-landing-language') || 'en');
})();
